version: "3.1"

services:
  diego_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: diego_db
      MYSQL_ROOT_USER: diegoandres
      MYSQL_USER: diegoandres
      MYSQL_ROOT_PASSWORD: asd123
      MYSQL_PASSWORD: asd123
